sudo: false
language: go

os:
  - linux
  - osx

go:
  - 1.9.x
  - 1.10.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_install:
  - export PATH=$HOME/protobuf/bin:$PATH

install:
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf
    && curl -LO https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-$TRAVIS_OS_NAME-x86_64.zip
    && unzip protoc-3.5.1-$TRAVIS_OS_NAME-x86_64.zip
    && popd
