sudo: false
language: go

os:
  - linux
  - osx

go:
  - 1.13.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_install:
  - export PATH=$HOME/protobuf/bin:$PATH

install:
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf
    && curl -LO https://github.com/google/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-$TRAVIS_OS_NAME-x86_64.zip
    && unzip protoc-$PROTOBUF_VERSION-$TRAVIS_OS_NAME-x86_64.zip
    && popd
